message = {
    "send_one_client": "verify if you have passed all parameters needed: --client_id or -ci --cpf_number or -cn",
    "delete_one_client": "verify if you have passed all parameters needed: --client_id or -ci",
    "send_one_account": "verify if you have passed all parameters needed: --compe_code or -cc --client_id or -ci --branch_code or -bc --number or -n --account_type or -at --account_subtype or -ast --description or -d --check_digit or -cd --currency or -c --account_id or -ai",
    "delete_one_account": "verify if you have passed all parameters needed: account_id or -ai",
    "send_one_pre_paid_transaction": "verify if you have passed all parameters needed: --transaction_id or -ti --transaction_date or -td --amount or -a --transaction_currency or -tc --credit_debit_type or -cdt --transaction_name or -tn --category or -ct --account_id or -ai --request_id or -ri --partie_cnpj_cpf or -pcc --transaction_model_type or -tmt --partie_compe_code or -pccd --partie_branch_code or -pbc --partie_number or -pn --partie_check_digit or -pcd --completed_authorised_payment_type or -capt",
    "delete_one_transaction": "verify if you have passed all parameters needed: --transaction_id or -ti",
    "default_message": "choose a valid option: --send_one_client or -soc --delete_one_client or -doc --send_clients or -sc --delete_clients or -dc --send_one_account or -soa --delete_one_account or -doa --send_accounts or -sa --delete_accounts or -da --send_one_pre_paid_transaction or -soppt_1 --delete_one_transaction or -dot --send_pre_paid_transactions or -sppt_1 --delete_transactions or -dt examples: python3 file_name.py --send_one_client --client_id test123 --cpf_number 12345678900 python3 file_name.py --delete_one_client --client_id test123 python3 file_name.py --send_clients python3 file_name.py --delete_clients python3 file_name.py --send_one_account --compe_code 001 --client_id account_test_1 --branch_code 0001 --number 00000 --check_digit 0 --account_type CONTA_DEPOSITO_A_VISTA --account_subtype INDIVIDUAL --description the test request --currency BRL --account_id 0 python3 file_name.py --delete_one_account --account_id test123 python3 file_name.py --send_accounts python3 file_name.py --delete_accounts python3 file_name.py --send_one_pre_paid_transaction --transaction_id 1 --transaction_date 2022-01-01 00:00:00.000 --amount 1.0 --transaction_currency BRL --credit_debit_type CREDITO --transaction_name transaction --category uber --account_id 1 --request_id 1 --partie_person_type PESSOA_NATURAL --partie_cnpj_cpf 00000000000 --transaction_model_type PIX --partie_compe_code 001 --partie_branch_code 11245 --partie_number 158964 --partie_check_digit 1 --completed_authorised_payment_type TRANSACAO_EFETIVADA",
}
